### ISSUE TITLE
Fastly - Theme caching issue

### ISSUE THREAD

**Issue by abhimotee** [fastly/fastly-magento2#289]
Hello,

We are experiencing an issue with Fastly caching in M2.3.1. We are setting different theme for the desktop and mobile. The mobile theme will load only with specific user agent, set within Magento admin configuration. 

We noticed that with Fastly on, if it caches the mobile theme, then all users are seeing the mobile theme irrespective of the user agent.

We confirmed it was Fastly related as when Fastly is disabled on our staging environment, the theme is cached and loaded properly per user agent.

Can you please advise if this is a known issue and if there is any workaround for this?

**Comment by abhimotee** [comment]
Hello,

Can anyone help us on the above issue?

**Comment by vvuksan** [comment]
Hi,

This is related to our stock VCL stripping out Vary: User-Agent since in nearly all cases Varying on User-Agent results in low cache hit ratio

https://github.com/fastly/fastly-magento2/blob/master/etc/vcl_snippets/fetch.vcl#L32

Quickest way to fix this by combining this solution 

https://docs.fastly.com/guides/vcl-tutorials/delivering-different-content-to-different-devices

by adding following two snippets

Snippet 1

Name: normalize_user_agent
Type: vcl_recv/recv
Priority: 10
Content:
```
if (req.http.User-Agent ~ "(?i)ip(hone|od)" || req.http.User-Agent ~ "(?i)android" ) {
   set req.http.X-UA-Device = "mobile";
} else {
   set req.http.X-UA-Device = "desktop";
}
```

Feel free to add matching for any other user agent aboves

Snippet 2

Name: change_user_agent_vary
Type: vcl_fetch/fetch
Priority: 10
Content:
```
if ( beresp.http.Vary ) {
   set beresp.http.Vary = regsub(beresp.http.Vary, "User-Agent", "X-UA-Device");
}
```

**Comment by abhimotee** [comment]
Hello,

Thanks for the reply. It seems to work except for the Magento homepage.

Is there anything else we need for the homepage?

**Comment by vvuksan** [comment]
It would appear home page is not setting the proper Vary header so you could possibly adjust the snippet `change_user_agent_vary` and add 

```if ( req.url.path == "/" ) {
   set beresp.http.Vary = "Accept-Encoding, X-UA-Device";

**Comment by vvuksan** [comment]
This functionality is now supported by a Fastly Edge Module

https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/Edge-Modules/EDGE-MODULE-MOBILE-THEME-SUPPORT.md
