### ISSUE TITLE
Image Optimization not being applied for admin pages

### ISSUE THREAD

**Issue by sivasdescalzo** [fastly/fastly-magento2#366]
We have noticed that Image Optimization is only applying for frontend request, and not on admin pages.
For instance, admin product grid renders product images from the path media/catalog/product/cache, this has a huge impact on PHP servers which still have to manage get.php requests and generate Magento media cache files.

**Comment by vvuksan** [comment]
Can you verify that images from /media/catalog/product/cache are in fact cacheable e.g. by inspecting the Cache-Control headers. If images are not cacheable IO transformations will not run.

**Comment by mpchadwick** [comment]
Noticed the same behavior and was coming to see if anyone else opened an issue about the same. Specifically, on the product grid the requests still go through Magento cache directory for thumbnails:

media/catalog/product/cache/thumbnail/

**Comment by vvuksan** [comment]
We'll look into this.

**Comment by MartinPeverelli** [comment]
Hi all!
Using cache systems is really not the best way to deal with things on the Admin side of Magento. The standard way is for users of the Admin to be able to see the data as close to as raw as possible, and for images, it would mean to see and manipulate the real and original source of truth. 

It would be based on these images, as seen from the Admin, that then cache layers can fetch them and optimize, distribute, etc. But you would want for the real image files to be visible from the Admin without any middleman.

Does this makes sense? This is the reason behind excluding the Admin from most (if not all) Fastly caching mechanisms.

Thanks!

**Comment by mpchadwick** [comment]
I'm not sure I agree. On the admin product grid the admin user could load 10s or even 100s of product images. If these are not resized page load will be severely negatively impacted by loading full size image. While it makes sense to load full size image when admin user clicks into product to edit, for the grid resized images make sense. This is currently Magento out of box behavior when loading product grid...it resizes images. The issue is that resizing on admin product grid is still made Magento's responsibility, however the value prop of this feature is it offloads that functionality so Magento no longer is responsible for it.

**Comment by MartinPeverelli** [comment]
@mpchadwick ah, I understand now, and I agree that we should look into it. Thanks!

**Comment by MartinPeverelli** [comment]
Hi all!
Sorry it took this long to reply to make it formal, but in case anyone else sees this, starting from version 1.2.137 we are now using Fastly's Image Optimization for the backend as well as the frontend. This also allows cron processes that make use of the product images (such as sitemap generators) to use the correct images.
Thanks!
