### ISSUE TITLE
Scheduled Block Updates Not Purging Cache Tags

### ISSUE THREAD

**Issue by beechyrb** [fastly/fastly-magento2#406]
When scheduling block updates in Magento **Content** >> **Blocks** using the Scheduled Update functionality that comes with Magento Cloud the Fastly cache tags do not become invalidated and Fastly continues to serve stale content. Normal saves to Blocks work as expected it is just the Scheduled Update feature that doesn't work.

Screenshot of Scheduled Update feature for clarity: ![Image](https://i.ibb.co/vkZ9tJ4/2020-08-25-20-54-50.png)

Platform: Magento Commerce Cloud
PHP 7.2
Magento v2.3.4
Fastly v1.2.146

**Comment by MartinPeverelli** [comment]
@beechyrb You are 100% correct and sadly this is a bug within Magento.
To be specific, when Scheduled updates are applied, there is a process that runs through all the elements in that update and adds their cache tags to a list of tags to be cleared.
Our module then correctly picks up that list, and sends those tags to be cleared on Fastly.

The problem is that Magento is missing the entire implementation for CMS Blocks. That means that no blocks updated via a schedule are ever added to this list.

This is only a Cloud/Enterprise issue, so I've already raised it internally on the Magento Engineering Comms for them to give us an update or patch.

I'll keep this updated as this develops.

Thanks!

**Comment by beechyrb** [comment]
Thanks, I was wondering about that but had not checked. I have a ticket going with Magento as well so I asked them to attach the issue you raised with my ticket.

**Comment by beechyrb** [comment]
Magento support provided a patch for this issue so if anyone needs this they can reference MDVA-32956. Note this is only for enterprise edition. I assume it will be included in a release in the near future.
