### ISSUE TITLE
Fastly module breaks interface contract

### ISSUE THREAD

**Issue by ihor-sviziev** [fastly/fastly-magento2#466]
Hi,

This is follow up to the https://github.com/magento/magento2/pull/33468#issuecomment-878927649

Pre-history: In Magento at some point was delivered a fix for incorrect return type for `\Magento\PageCache\Model\Config::getType()` in https://github.com/magento/magento2/commit/b59dc722059f3a87716a41dc0f5ae62ec297fb69#diff-1281464bcdc813265cb8b0e9822464bd0504743ca81e31b00d46a8b600c9b770R124

Later on, as Magento Cloud using Fastly as CDN provider, this change was partly reverted in https://github.com/magento/magento2/commit/1778c0f73570f19f9f368a18ff0808a6177f96e2, which caused another issue - more details see in https://github.com/magento/magento2/pull/33468.

Root cause analysis shown, that issue coming to the Fastly extension, as it introduced value "fastly" (string) for the method "getType", then converting it to integer (as method designed to return integer) just breaks Fastly extension.
https://github.com/fastly/fastly-magento2/blob/707ffb3779a1d3c7921b81a88a69c5613490a702/Observer/FlushAllCacheObserver.php#L61
https://github.com/fastly/fastly-magento2/blob/707ffb3779a1d3c7921b81a88a69c5613490a702/Model/Config.php#L48

Suggestion:
1. Change "type" from "fastly" to some integer value
2. Write a data upgrade script that will convert the old value to new one.

/CC @hostep

**Comment by dpotkoc** [comment]
Hello @ihor-sviziev  we are aware of issue and we are fine with your suggestion.

If we change "type" from "**fastly**" to some integer, which value is fine?

Magento is using next values:
`    const BUILT_IN = 1;`
`    const VARNISH = 2;`

I mean that we should use some number greater then 3, because Magento can use 3 for some other type of cache and then we will have issue / conflict.

What do you mean?

Thnx
Domagoj

**Comment by ihor-sviziev** [comment]
@dpotkoc, I think you can use some value greater than 10, maybe 100 is good enough.

**Comment by dpotkoc** [comment]
@ihor-sviziev thnx for answer, we will make modification.

Domagoj

**Comment by IgorVitol** [comment]
@ihor-sviziev @dpotkoc Updated fastly extension today and noted that it is no longer backward compatible. Our cloud stage env for some reason switched back to Built-in cache. Root cause is because of "fastly" was changed to "42".

Even with this, seems like image optimizations stopped to work:
```
if ($this->_scopeConfig->getValue(PageCacheConfig::XML_PAGECACHE_TYPE) !== Config::FASTLY) {
// ...
}
```
Such block doesn't pass, since "42" !== 42 is true.

As a temporary solution we have to downgrade back, to the older version.

**Comment by dpotkoc** [comment]
Hello @IgorVitol thnx for reporting, we will need to fix issue for image processing. I agree with you.

Regarding your claim "_Our cloud stage env for some reason switched back to Built-in cache. Root cause is because of "fastly" was changed to "42"._"
It will be good if you can send us steps how to reproduce. 

I think that Fastly worked fine but you had old value "fastly" exported in config.php file and dropdown in Magento admin section was not be able to preselect right option with fastly cache.

If you exported config to files we can't change file on your disc

We have plugin which is fixing issue if you have old vaule in config:  https://github.com/fastly/fastly-magento2/blob/86e0fa7c4253ffdcdba9e95765286e54ab277ddb/Model/PageCache/ConfigPlugin.php#L77

Thnx
Domagoj
