### ISSUE TITLE
Magento admin does not show all custom VCL snippets

### ISSUE THREAD

**Issue by Seppo-Konttinen-Solteq** [fastly/fastly-magento2#557]
Checking custom VCL snippets from Magento admin and comparing to list that is gotten via Fastly API:

`https://api.fastly.com/service/[fastly_service]/version/[version]/snippet`

Magento admin does not show all the custom VCL snippets that the Fastly API shows.

**Comment by vvuksan** [comment]
HI @Seppo-Konttinen-Solteq. This is by design. The UI inside the Magento Module was intended for limited management of snippets as there are some functions like Image Optimization and Force TLS that create their own snippets and we deemed it was going to be too crowded to have them listed in Module UI. I agree in some cases this may not be ideal however this was the tradeoff.
