### ISSUE TITLE
Configuration fields dont load if menu is already open

### ISSUE THREAD

**Issue by dfa-ds** [fastly/fastly-magento2#659]
We are using Adobe Commerce 2.4.6-p1 and the module fastly/fastly-magento2 in the version 1.2.201.

When we navigate to the admin area to Stores > Settings > Configurations > Advanced > System > Full Page Cache, we have the problem that we cant configure anything when the Menu "Fastly Configuration" is already open.

When we close the menu and refresh the page, it works.

The problem is the following code:
https://github.com/fastly/fastly-magento2/blob/214909cc024a4bda3f23aecca01005961fbaf3a3/view/adminhtml/web/js/init.js#L21

The function "init" is only triggered if you open the "Fastly Configuration".
Because the event is only fired once, it does not work to just close and open the menu.

But if its already open when entering the page, the init function should run without a click.

Here a screenshot of the corresponding menu element:
![image](https://github.com/fastly/fastly-magento2/assets/93194225/1b81c9c6-dcb3-4fda-b8cc-ef37ef3f4c56)

**Comment by ivanviduka** [comment]
Hi @dfa-ds 

you are correct, initialization is bind to click event on system_full_page_cache_fastly-head, and since the menu is already open, that initialization is never triggered.

However, the only way I was able to reproduce this problem is by opening my Admin page with anchor #system_full_page_cache_fastly-link on the end of URL. In all other variation i tried, the menu was closed and everything worked fine.

Can you please inform me how can I reproduce this problem - does it occur in some other cases or do you have #system_full_page_cache_fastly-link tag in your URL as well?

**Comment by dfa-ds** [comment]
Hi @ivanviduka ,
thank you for reviewing my issue.

I dont have the anchor in my url.
The state of open menus is somehow saved in my admin account but I have not figured out yet where the information is stored.
I tried to clear my browser cookie and storage and logged in again, but the menu state was still saved.
Maybe my session is restored after login?

I'm sorry that I cant provide more information to that yet.

Our workaround is right now to close the the menu and reload the page.

**Comment by ivanviduka** [comment]
Hi @dfa-ds 

I will look into it a bit more and try to reproduce and solve the issue. If you find any more information, please let us know.
